require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "script/**/*"
    - "vendor/**/*"
    - "Rakefile"
    - "config.ru"
    - "Gemfile"
  TargetRubyVersion: 3.2

Style/Documentation:
  Exclude:
    - !ruby/regexp /application_.*\.rb$/