volumes:
  gem_data:
  mysql_data:
services:
  db:
    restart: always
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
  web:
    build: .
    command: bash -c "rm -rf tmp/pids/server.pid && ./bin/dev"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: gem_data
        target: /usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
